Bringing repo (now managed by Git) up to date after many changes.

diff --git a/handle-email b/handle-email
--- a/handle-email
+++ b/handle-email
@@ -4,13 +4,30 @@
 #   $1: who fetchmail thinks it's from
 #   $2: the name of the local user who ran fetchmail
 
-if [ "$1" = "" ]; then
-  echo "usage: $0 from-addr local-user < message"
-  exit
-fi
+if [ "$1" = "-manual" ]; then
+  # this is for running manually, when a message gets mis-classifed
+  export -n QMAILINJECT
+  export -n MAILUSER
+  export -n MAILHOST
+  export -n MAILNAME
+  shift
+fi  
 
-from="$1"
-localUser="$2"
+if [ "$1" = "" -a "$2" = "" ]; then
+  if [ "$FORCE_EMAIL" = "yes" ]; then
+    # 8/21/03: someone sent me an email that contained a "From:" header,
+    # but the rest of the line was blank; I think fetchmail set $1 to "",
+    # thus confusing me.  if I see it again I might try to detect it
+    from="someone@somewhere.com"
+    localUser="$USER"
+  else
+    echo "usage: $0 from-addr local-user < message"
+    exit
+  fi
+else
+  from="$1"
+  localUser="$2"
+fi
 
 # send any output this script generates to a file
 exec >>"$HOME/tmp/var/handle-email.err" 2>&1
@@ -33,8 +50,11 @@ sexual='fuck|piss|cock|pervert|naked|britney|porn|pheromones|tits|nude'
 suggestive='amateur|adult|girl|prescription|zyban|viagra'
 
 # strings in the 'from' which automatically make it not spam
-friends="johnmcpeak|sunnemcpeak|toddmcpeak|smcpeak|\
-necula|mirabito|weimer|dsw|hurwitz|aclu.org|harmonia|gm3576|aycock"
+# had to remove 'smcpeak' because the spammers like to fill in my
+# own address as the 'from' line
+friends="johnmcpeak|sunnemcpeak|toddmcpeak|johnloff|\
+necula|mirabito|weimer|dsw|hurwitz|aclu.org|harmonia|gm3576|aycock|\
+ashleybanana|mcpeak6|ralphpboland|todd|josefrisco|ashleymcpeak"
 
 # these are grepped in the subject
 scoreTwo='income|scott.*mcpeak|toner'
@@ -42,15 +62,23 @@ scoreThree='mortgage.*rates|special.*offer'
 scoreFour='make.*money|output.*from.*cron'
 
 # these are grepped in the body
-scoreThreeBody='one  *time  *advertisement|eudoramail\.com|this is not spam|click  *here'
+scoreThreeBody='one  *time  *advertisement|eudoramail\.com|this is not spam|click  *here|<font color="#ffffff">'
+
+scoreFourBody='Found virus [^ ]+ in file|e-hostzz\.'
 
 # specific known spammers who use consistent 'from' addresses;
 # spam from these people isn't even logged
-spamFrom='customoffers\.com|The Investment Journal|s.*t.*a.*y.*h.*a.*r.*d|choiceoffers\.smtp0\.net|investor relations|hotpop\.com'
+spamFrom='customoffers\.com|The Investment Journal|s.*t.*a.*y.*h.*a.*r.*d|choiceoffers\.smtp0\.net|investor relations|hotpop\.com|darkprofits'
 
 # send email message to a temporary file
 msg="$HOME/tmp/var/msg/msg.$$"
-cat >"$msg"
+if cat >"$msg"; then
+  true
+else
+  # this is to avoid accepting email when the disk is full
+  echo "[$$] cat failed!"
+  exit 2
+fi
 
 # log some information about the email
 log="$HOME/tmp/var/handle-email.log"
@@ -148,6 +176,12 @@ else
   oneTimeAdvert=0
 fi
 
+if egrep -i "$scoreFourBody" <"$msg" >/dev/null; then
+  scoreFourB=4
+else
+  scoreFourB=0
+fi
+
 # known spammer
 if grep '^From:' <"$msg" | egrep -i "$spamFrom" >/dev/null; then
   spammerSource=4
@@ -163,8 +197,10 @@ else
 fi
 
 # use of sexual words?  count lines which have them
-naughty=`egrep -i "$sexual" <"$msg" | wc -l`
-naughty=$[ $naughty ]
+#naughty=`egrep -i "$sexual" <"$msg" | wc -l`
+#naughty=$[ $naughty ]
+# the above is falsely-flagging too many messages..
+naughty=0
 
 # use of suggestive words?  count lines which have them
 suggCt=`egrep -i "$suggestive" <"$msg" | wc -l`
@@ -253,6 +289,13 @@ else
   javascript=0
 fi
 
+# is it one of the three-liners?
+if egrep -i '<html><body>smcpeak' <"$msg" >/dev/null; then
+  threeLiner=4
+else
+  threeLiner=0
+fi
+
 # is the message in base64?
 #  if grep -i '^Content-Transfer-Encoding: base64' <"$msg" >/dev/null; then
 #    messageBase64=4
@@ -278,6 +321,14 @@ else
   big5=0
 fi
 
+# does the EECS filter think it's spam?  this tests for
+# a "level" of 5 or more
+if grep '^X-Spam-Level: \*\*\*\*\*' <"$msg" >/dev/null; then
+  eecsSaysSpam=4
+else
+  eecsSaysSpam=0
+fi
+
 
 # ---------- check for things which are *not* spam --------
 # email from Mom/Dad, which happens to originate at yahoo or aol
@@ -300,6 +351,7 @@ score=$[ $fromFree +          \
          $income +            \
          $specialOffer +      \
          $oneTimeAdvert +     \
+         $scoreFourB +        \
          $spammerSource +     \
          $makeMoney +         \
          $naughty +           \
@@ -317,6 +369,8 @@ score=$[ $fromFree +          \
          $messageBase64 +     \
          $bulkHeader +        \
          $big5 +              \
+         $eecsSaysSpam +      \
+         $threeLiner +        \
          $friends ]
 
 # log the analysis results
@@ -331,6 +385,7 @@ echo "[$$] ($score) " \
      "income=$income " \
      "specialOffer=$specialOffer " \
      "oneTimeAdvert=$oneTimeAdvert " \
+     "scoreFourB=$scoreFourB " \
      "spammerSource=$spammerSource " \
      "makeMoney=$makeMoney " \
      "naughty=$naughty " \
@@ -348,12 +403,21 @@ echo "[$$] ($score) " \
      "messageBase64=$messageBase64" \
      "bulkHeader=$bulkHeader" \
      "big5=$big5" \
+     "eecsSaysSpam=$eecsSaysSpam" \
+     "threeLiner=$threeLiner" \
      "friends=$friends " >>"$log"
+
+if [ "$SCORE_OVERRIDE" != "" ]; then
+  # this is a command-line override number I've specified
+  score="$SCORE_OVERRIDE"
+fi
 
 # test against threshold
 if [ $score -ge $threshold ]; then
   # spam!
-  ln -f "$msg" "$spamDir"         
+  rm -f "${msg}.gz"
+  gzip "$msg"
+  ln -f "${msg}.gz" "$spamDir"
   # log it, unless it's that damned 'customoffers.com', in which case
   # don't even pollute my log with that trash
   if [ $spammerSource = 0 ]; then
@@ -366,9 +430,21 @@ else
   # deliver the email to my Mailbox
   if ! /usr/sbin/sendmail -oem -f "$from" "$localUser" <"$msg"; then
     # print a message to my log, but otherwise drop it on floor
-    # (relying on its being retained in $msg)
+    # (relying on it being retained in $msg)
     echo "[$$] qmail choked on message" >>"$log"
+
+  else
+    # wait just a sec so qmail has time to deliver it (otherwise sometimes
+    # my message is scrolled beyond the part I can see easily)
+    sleep 1
+
+    # print a log message too, so I can see who it's from w/o clicking on pine
+    logger -t handle-email "[$$] new mail from $from, $subject"
   fi
+
+  # compress it
+  rm -f "${msg}.gz"
+  gzip "$msg"
 fi
 
 # remove the temporary message
diff --git a/mozilla b/mozilla
--- a/mozilla
+++ b/mozilla
@@ -1,6 +1,8 @@
 #!/bin/bash
 # run mozilla (/bin/bash for $[...] syntax)
 
+echo "$@" >/tmp/mozilla.invoke.tmp
+
 # this is for slack 7 install
 top=/home/scott/bin          
 
@@ -10,21 +12,18 @@ if [ -d /home/scott/opt ]; then
 fi
 
 # defaults
-moz=$top/mozilla-1.1
-
-# I hacked es1371 so this can default to yes!!
-flash=yes
+moz=$top/mozilla-1.7.8
 
 while [ "$1" != "" ]; do
   case "$1" in
     -prev)
-      moz=$top/mozilla-1.0
+      moz=$top/mozilla-1.7.2
       ;;
 
     -flash)
       flash=yes
       ;;
-      
+
     -noflash)
       flash=no
       ;;
@@ -33,67 +32,63 @@ while [ "$1" != "" ]; do
   shift
 done
 
-# remove buggy plugins
-rm -f $moz/plugins/ShockwaveFlash.class
-rm -f $moz/plugins/libflashplayer.so
+#  # link in Flash plugins
+#  if [ ! -f $moz/plugins/libflashplayer.so ]; then
+#    ln -s ~/dist/plugins/libflashplayer.so $moz/plugins
+#    ln -s ~/dist/plugins/flashplayer.xpt $moz/plugins
+#  fi
 
-# optionally add them back in
-if [ "$flash" = "yes" ]; then
-  ln -s ~/dist/plugins/ShockwaveFlash.class $moz/plugins
-  ln -s ~/dist/plugins/libflashplayer.so $moz/plugins
-fi
-
-# if java isn't in, add it
-if [ ! -L $moz/plugins/libjavaplugin_oji*.so ]; then
-  echo "Linking java plugin.."
-  ln -s ~/dist/plugins/*java* $moz/plugins
-fi
+#  # if java isn't in, add it
+#  if [ ! -L $moz/plugins/libjavaplugin_oji*.so ]; then
+#    echo "Linking java plugin.."
+#    ln -s ~/dist/plugins/*java* $moz/plugins
+#  fi
 
 
-# It turns out Mozilla occasionally blows away my history file!
-#   see bug reports 77514, 102519, 94827
-# So I will save my history file each time it starts, *provided*
-# the new history is at least as long as the old one! (If the
-# history is so long it's being truncated, on average this should
-# save it every other time.)  I will automatically restore from
-# backup whenever the history file seems to have shrunk by more
-# than 5kbytes.
-bak=$HOME/bak/history.dat
-userdir=`echo $HOME/.mozilla/$USER/*`
-cur=$userdir/history.dat
+#  # It turns out Mozilla occasionally blows away my history file!
+#  #   see bug reports 77514, 102519, 94827
+#  # So I will save my history file each time it starts, *provided*
+#  # the new history is at least as long as the old one! (If the
+#  # history is so long it's being truncated, on average this should
+#  # save it every other time.)  I will automatically restore from
+#  # backup whenever the history file seems to have shrunk by more
+#  # than 5kbytes.
+#  bak=$HOME/bak/history.dat
+#  userdir=`echo $HOME/.mozilla/$USER/*`
+#  cur=$userdir/history.dat
 
-if [ ! -d $HOME/bak ]; then
-  # make this directory; I put my emacs backups here too, so it's
-  # a convenient place for me
-  mkdir $HOME/bak
-fi
+#  if [ ! -d $HOME/bak ]; then
+#    # make this directory; I put my emacs backups here too, so it's
+#    # a convenient place for me
+#    mkdir $HOME/bak
+#  fi
 
-if [ ! -f $bak ]; then
-  echo "Backup history file doesn't exist; making initial backup."
-  cp -f $cur $bak
-elif [ ! -f $cur ]; then
-  echo "History file is gone!  Restoring from backup."
-  cp $bak $cur
-else
-  # interpreting the 5th field as the size may run afoul of
-  # some systems' "ls" which doesn't print group information...
-  # I don't know a simple solution
-  baksize=`ls -l $bak | awk '{ print $5 }'`
-  cursize=`ls -l $cur | awk '{ print $5 }'`
+#  if [ ! -f $bak ]; then
+#    echo "Backup history file doesn't exist; making initial backup."
+#    cp -f $cur $bak
+#  elif [ ! -f $cur ]; then
+#    echo "History file is gone!  Restoring from backup."
+#    cp $bak $cur
+#  else
+#    # interpreting the 5th field as the size may run afoul of
+#    # some systems' "ls" which doesn't print group information...
+#    # I don't know a simple solution
+#    baksize=`ls -l $bak | awk '{ print $5 }'`
+#    cursize=`ls -l $cur | awk '{ print $5 }'`
 
-  if [ $[ $baksize / 2 ] -gt $cursize ]; then
-    echo "Backup history file is more than twice as long as the old history!"
-    ls -l $cur
-    ls -l $bak
-    echo "Bailing so you can decide what to do."
-    exit 2
-  else
-    # normal case: silently replace backup with current history,
-    # thereby keeping it up-to-date
-    cp -f $bak $bak.bak
-    cp -f $cur $bak
-  fi
-fi
+#    if [ $[ $baksize / 2 ] -gt $cursize ]; then
+#      echo "Backup history file is more than twice as long as the old history!"
+#      ls -l $cur
+#      ls -l $bak
+#      echo "Bailing so you can decide what to do."
+#      exit 2
+#    else
+#      # normal case: silently replace backup with current history,
+#      # thereby keeping it up-to-date
+#      cp -f $bak $bak.bak
+#      cp -f $cur $bak
+#    fi
+#  fi
 
 
 # the java plugin makes a stupid trace file in my home dir.. so wait
@@ -117,7 +112,8 @@ hideTheTrace()
 
 # one of the reasons for 'exec' here is so that I can freely edit
 # this script while mozilla is still running
-exec nohup $moz/mozilla -P scott >/dev/null 2>&1
+#exec nohup $moz/mozilla -P scott "$@" >/dev/null 2>&1
+exec nohup $moz/mozilla "$@" >/dev/null 2>&1
 
 
 # shouldn't get here
diff --git a/start-xclock b/start-xclock
--- a/start-xclock
+++ b/start-xclock
@@ -7,23 +7,17 @@ if ! which $xclock >/dev/null 2>&1; then
   xclock=xclock
 fi
 
-if [ -f /etc/slack8 ]; then
-  # kde2: use kstart
-  kstart --type Dock $xclock -digital -update 1 -geometry 191x29+0-2
-  sleep 1
+kstart --type Dock -window xclock $xclock -digital -update 1 -geometry 191x22+0-0
+sleep 1
 
-  # move it where I want it since kde doesn't respect geometry
-  id=`xwininfo -name $xclock | grep "Window id" | awk '{ print $4 }'`
-  id=$id
-  if [ "$id" = "" ]; then
-    echo "Couldn't find the right window id"
-    exit 2
-  fi
-
-  # 'movewin' is a program I wrote (~/wrk/learn/x/movewin.cc)
-  movewin $id -move 0 1002 -lower
-
-else
-  # kde1
-  $xclock -digital -update 1
+# move it where I want it since kde doesn't respect geometry
+id=`xwininfo -name $xclock | grep "Window id" | awk '{ print $4 }'`
+id=$id
+if [ "$id" = "" ]; then
+  echo "Couldn't find the right window id"
+  exit 2
 fi
+
+# 'movewin' is a program I wrote (~/wrk/learn/x/movewin.cc)
+#movewin $id -llcorner -move 0 1002 -size 200 38 -lower
+movewin $id -lower
