another snapshot after long time of no attention to cvs

diff --git a/rename-by-filter b/rename-by-filter
--- a/rename-by-filter
+++ b/rename-by-filter
@@ -18,10 +18,14 @@ for fname in "$@" ; do
   # generate new name
   newname=`echo $fname | $filter`
 
-  # rename and try not to clobber anything
-  # if it fails, stop immediately
-  echo "renaming $fname to $newname"
-  mv -i $fname $newname || exit
+  if [ "$newname" = "$fname" ]; then
+    echo "skipping $fname -- new name is identical"
+  else
+    # rename and try not to clobber anything
+    # if it fails, stop immediately
+    echo "renaming $fname to $newname"
+    mv -i $fname $newname || exit
+  fi
 done
 
 
